on:
  pull_request:
  push:
    branches:
      - '*'

name: Tests

jobs:

  test:
    name: Build and Test (${{ matrix.buildvariant }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildvariant: [ FossNormal, FossAutomotive, GoogleNormal, GoogleAutomotive ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Copy apikeys.xml
        run: cp .github/workflows/apikeys-ci.xml app/src/main/res/values/apikeys.xml

      - name: Build app
        run: ./gradlew assemble${{ matrix.buildvariant }}Debug --no-daemon
      - name: Run unit tests
        run: ./gradlew test${{ matrix.buildvariant }}DebugUnitTest --no-daemon
      - name: Run Android Lint
        run: ./gradlew lint${{ matrix.buildvariant }}Debug --no-daemon
      - name: Upload GoogleNormal artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoogleNormal_debug
          path: app/build/outputs/apk/googleNormal/debug/app-google-normal-debug.apk
      - name: Upload GoogleAutomotive artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoogleAutomotive_debug
          path: app/build/outputs/apk/googleAutomotive/debug/app-google-automotive-debug.apk
